### ISSUE TITLE
Ubuntu 16.04 (Xenial Xerus)

### ISSUE THREAD

**Issue by seniorihor** [lvillani/i3-gnome#5]
How about support of the current Ubuntu LTS version?

**Comment by lvillani** [comment]
I'm not using Ubuntu (or Linux) as my daily driver at the moment so that's unlikely to come from me for the time being.

**Comment by lvillani** [comment]
By the way this is related to #3

**Comment by lvillani** [comment]
I'm closing this and will track this one in #3
