### ISSUE TITLE
Mode drun not enabled ?

### ISSUE THREAD

**Issue by killajoe** [lvillani/i3-gnome#7]
I get this messages on journal:
```
Sep 07 22:58:08 empowered64 i3-gnome.desktop[13289]: Mode drun not enabled. Please add it to the list of enabled modi: window,run,ssh
Sep 07 22:58:08 empowered64 i3-gnome.desktop[13289]: Adding mode: drun
```
Could be related to rofi also but it comes up from i3-gnome.desktop...

running AUR package, and Antergos Linux

Thanks a lot for sharing i3-gnome!

**Comment by 51v4n** [comment]
Hello, thanks for your interest in i3-gnome.
I'm not understanding what `Mode drun` actually does, i'm not getting any helpful documentation around (i'll take time for this).
Are you on serious trouble whit this? can you give the same output for rofi? thanks in advance.
Cheers!

**Comment by killajoe** [comment]
No i am not in real trouble with this! 
drun is the mode from rofi where it uses only the program.desktop entries for the search-menu:
[rofi-drun](https://img3.picload.org/image/dggidclr/drun.png)
I was only wondering why this is shown up for i3-gnome.desktop in the journal.
On a second thinking about i do not think it is related to i3-gnome at all...

**Comment by 51v4n** [comment]
Ok got it, not an issue at all. Closing.
Thanks for caring!
