### ISSUE TITLE
GNOME 3.26 update 

### ISSUE THREAD

**Issue by killajoe** [lvillani/i3-gnome#9]
Seems to not work anymore after the update today
-Arch Linux with GDM or lightdm
-try to login the session brings you right back to the DM

**Comment by 51v4n** [comment]
Let's see, last time when something similar happened, it was about certain components of the session. In first instance i think we have same here, but i'm assuming, i'll find out what's going on.
Thanks for let me know.

**Comment by killajoe** [comment]
i can provide logs e.t.c. if it will help...

**Comment by killajoe** [comment]
`[killajoe@empowered64 ~]$ cat /usr/bin/gnome-session
#!/bin/sh

if [ "x$XDG_SESSION_TYPE" = "xwayland" ] &&
   [ "x$XDG_SESSION_CLASS" != "xgreeter" ] &&
   [  -n "$SHELL" ] &&
   grep -q "$SHELL" /etc/shells &&
   ! (echo "$SHELL" | grep -q "false") &&
   ! (echo "$SHELL" | grep -q "nologin"); then
  if [ "$1" != '-l' ]; then
    exec bash -c "exec -l '$SHELL' -c '$0 -l $*'"
  else
    shift
  fi
fi

SETTING=$(gsettings get org.gnome.system.locale region)
REGION=${SETTING#\'}
REGION=${REGION%\'}

if [ -n "$REGION" ]; then
  export LC_TIME=$REGION
  export LC_NUMERIC=$REGION
  export LC_MONETARY=$REGION
  export LC_MEASUREMENT=$REGION
  export LC_PAPER=$REGION
fi

exec /usr/lib/gnome-session/gnome-session-binary "$@"`

**Comment by 51v4n** [comment]
Please, it would be a lot helpful, any help is greatly appreciated.

**Comment by 51v4n** [comment]
FWIW, i'm just comparing changes between files under `/usr/share/gnome-session/sessions`:
`$ diff -y i3-gnome.session gnome.session`
`[GNOME Session]							[GNOME Session]`
`Name=GNOME						      |	Name=i3-gnome`
`RequiredComponents=org.gnome.Shell;org.gnome.SettingsDaemon.A|RequiredComponents=org.gnome.SettingsDaemon.A11yKeyboard;org.
`

Also i'm checking out `/usr/lib/gnome-settings-daemon/` [because of last time](https://bugs.archlinux.org/task/53800)

**Comment by killajoe** [comment]
```
gnome-settings-daemon]$ ls
gsd-a11y-keyboard     gsd-housekeeping    gsd-print-notifications  gsd-wacom
gsd-a11y-settings     gsd-keyboard        gsd-rfkill               gsd-wacom-led-helper
gsd-backlight-helper  gsd-locate-pointer  gsd-screensaver-proxy    gsd-wacom-oled-helper
gsd-clipboard         gsd-media-keys      gsd-sharing              gsd-xsettings
gsd-color             gsd-mouse           gsd-smartcard
gsd-datetime          gsd-power           gsd-sound
gsd-dummy             gsd-printer         gsd-test-input-helper
```

**Comment by killajoe** [comment]
https://imgur.com/a/5iJjU

**Comment by 51v4n** [comment]
Thanks for that, i checked the `gsd-xsettings` script and i want to know if you have the same output from it, could you share what's on the same script?, because if it's the same situation to everyone we know what issue  have to fix.
Here's what's going on mine:
[Trying to check out the gsd-xsettings script](https://imgur.com/a/MFO6j)

**Comment by 51v4n** [comment]
Also, i filled a request on GNOME's bugzilla asking what's new about `gnome-session` to know what are the changes we have to focus on, that's why `i3-gnome` crashed last time.

**Comment by killajoe** [comment]
https://i.imgur.com/aMDvgnt.png

**Comment by killajoe** [comment]
http://kamprad.net/Downloads/gsd-xsettings.txt

**Comment by Snowmobil** [comment]
Just started using this today.
I removed Xrandr and Orientation from the RequiredComponents and it works now.

**Comment by 51v4n** [comment]
Amazing!, i did like you suggest and it works now.
Thanks!
The update will include your suggestion.

**Comment by 51v4n** [comment]
Considering this as fixed, updated now.

**Comment by Snowmobil** [comment]
Might be useful to have this on the record here:
https://github.com/GNOME/gnome-settings-daemon/blob/master/NEWS
Version 3.25.4
XRandR and Orientation - Removed - functionality migrated to mutter

**Comment by 51v4n** [comment]
Absolutely, thanks for that, it's kind of curious how parts of GNOME like this change trough time, i'll keep an eye closely to track new changes as soon as possible.

BTW, if you find something interesting and want to share, PR's are welcome :)
Cheers!
